export const INDONESIA_CITIES = [
  "Jakarta Pusat", "Jakarta Utara", "Jakarta Barat", "Jakarta Selatan", "Jakarta Timur",
  "Bandung", "Kabupaten Bandung", "Bandung Barat", "Cimahi", "Bekasi", "Kabupaten Bekasi",
  "Bogor", "Kabupaten Bogor", "Depok", "Tangerang", "Tangerang Selatan", "Kabupaten Tangerang",
  "Cirebon", "Sukabumi", "Garut", "Tasikmalaya", "Karawang", "Purwakarta", "Subang",
  "Sumedang", "Indramayu", "Majalengka", "Kuningan", "Ciamis", "Banjar", "Cianjur",
  "Surabaya", "Malang", "Kabupaten Malang", "Batu", "Sidoarjo", "Gresik", "Mojokerto",
  "Kediri", "Blitar", "Madiun", "Jember", "Banyuwangi", "Probolinggo", "Pasuruan",
  "Tuban", "Lamongan", "Bojonegoro", "Nganjuk", "Ponorogo", "Pacitan", "Trenggalek",
  "Tulungagung", "Bangkalan", "Sampang", "Pamekasan", "Sumenep",
  "Semarang", "Kabupaten Semarang", "Solo", "Surakarta", "Magelang", "Kabupaten Magelang",
  "Salatiga", "Pekalongan", "Tegal", "Kudus", "Jepara", "Pati", "Rembang", "Blora",
  "Grobogan", "Demak", "Kendal", "Batang", "Pemalang", "Brebes", "Banyumas",
  "Purwokerto", "Cilacap", "Kebumen", "Purworejo", "Wonosobo", "Temanggung", "Klaten",
  "Boyolali", "Sukoharjo", "Wonogiri", "Sragen", "Karanganyar",
  "Yogyakarta", "Sleman", "Bantul", "Kulon Progo", "Gunungkidul",
  "Denpasar", "Badung", "Gianyar", "Tabanan", "Klungkung", "Bangli", "Karangasem",
  "Buleleng", "Jembrana",
  "Medan", "Deli Serdang", "Binjai", "Pematangsiantar", "Tebing Tinggi", "Padang Sidempuan",
  "Padang", "Bukittinggi", "Payakumbuh", "Pekanbaru", "Batam", "Tanjungpinang",
  "Palembang", "Jambi", "Bengkulu", "Bandar Lampung", "Metro", "Pangkal Pinang",
  "Banda Aceh", "Lhokseumawe", "Sabang",
  "Makassar", "Palu", "Kendari", "Manado", "Gorontalo", "Mamuju",
  "Denpasar", "Mataram", "Kupang",
  "Balikpapan", "Samarinda", "Banjarmasin", "Banjarbaru", "Palangkaraya", "Pontianak",
  "Singkawang", "Tarakan",
  "Ambon", "Ternate", "Sorong", "Jayapura", "Manokwari",
];
